### PR TITLE
sig: Replace types of gems by upstream

### PR DESCRIPTION
**Pull request by tk0miya**
The types of commonmarker and rails-html-sanitizer are now registered to gem_rbs_collection.  They are **developed in this repo** and moved to common types repository now.

* https://github.com/ruby/gem_rbs_collection/pull/704
* https://github.com/ruby/gem_rbs_collection/pull/705

### CODE REVIEW

**Comment by tk0miya** [comment]
Two PRs from this repo are merged now:

* https://github.com/ruby/gem_rbs_collection/pull/702
* https://github.com/ruby/gem_rbs_collection/pull/700

**Comment by unasuke** [comment]
> They are developed in this repo

Great!!

**Comment by tk0miya** [comment]
Sorry, I forgot to update the rbs_collection.lock.yaml. I suppose now all tests are passed.

**Review by unasuke — APPROVED** [review]
👍

**Pull request merged**
