### PR TITLE
Determine the user is a organizer or participant

### PR DESCRIPTION
**Pull request by unasuke**
## what
From the GitHub API, get whether or not the user belongs to kaigionrails org on GitHub, and if so, set the role to organizer.

### CODE REVIEW

**Comment by unasuke** [comment]
memo 例外処理

**Comment by okuramasafumi** [comment]
@unasuke If this determination is done async, for a small amount of time admin users cannot be admin. I don't think it's a problem since it's usually seconds, but I'd like to confirm if it's no problem.

**Comment by unasuke** [comment]
@okuramasafumi Yes, there are no problems that I can think now.

**Review by okuramasafumi — APPROVED** [review]
🚀

**Pull request merged**
