### PR TITLE
Create type check action

### PR DESCRIPTION
**Pull request by fugakkbn**
Type check with GitHub Actions.
Run `steep validate` and `steep check`.

### CODE REVIEW

**Comment by unasuke** [comment]
@fugakkbn Could you use another file name e.g., `.github/workflows/typecheck.yml`

**Comment by fugakkbn** [comment]
@unasuke Sorry... I forgot to chenge it 😇
fixed [ffdcd5c](https://github.com/kaigionrails/conference-app/pull/33/commits/ffdcd5c0ce43f6c58333ebe7d5af4da39d6b20ff)

**Review by unasuke — COMMENTED** [review]
👍 👍 👍 👍

**Comment by fugakkbn** [comment]
Oops, merged by mistake...
Please revert if we have any problems.

**Pull request merged**
