### PR TITLE
Show flash messages

### PR DESCRIPTION
**Pull request by indigolain**
Should fix: https://github.com/kaigionrails/conference-app/issues/82
It looked like the flash message rendering was missing in the view template.
Feel free to tweak the designs if needed!

| success | alert |
----|---- 
| Screenshot 2023-10-29 at 19 16 20 | Screenshot 2023-10-29 at 19 36 23 |

### CODE REVIEW

**Review by unasuke — COMMENTED** [review]
Great!! Could you give me a screenshot to display an alert message?

**Comment by indigolain** [comment]
Sure! Added a screenshot showing the alert message in the description 👍

**Review by unasuke — APPROVED** [review]
_AWESOME_

**Comment by indigolain** [comment]
Thanks for the review!

**Pull request merged**
