### PR TITLE
RBS: Add User#organizer? manually

### PR DESCRIPTION
**Pull request by tk0miya**
As a preparation of updating types to the app, this adds types for `User#organizer?` manually because current rbs_rails does not support Rails7 style enums. It should be removed if rbs_rails will support it in the future.

### CODE REVIEW

**Comment by unasuke** [comment]
@tk0miya Could you also add `User#participant?` although it may not be used now?

**Comment by tk0miya** [comment]
> @tk0miya Could you also add `User#participant?` although it may not be used now?

Added :-)

**Review by unasuke — APPROVED** [review]
👍 👍 👍

**Review by fugakkbn — APPROVED** [review]
Thanks!

**Pull request merged**
