### PR TITLE
Add Planned features heading and implemented features list to README

### PR DESCRIPTION
**Pull request by hayaokimura**
Many awesome features are already implemented!

Add Planned features heading and implemented features list.

### CODE REVIEW

**Comment by unasuke** [comment]
@hayaokimura Not "No features implemented yet!" now. Could you update this sentence also?

**Comment by hayaokimura** [comment]
Thanks for your review!
OK. I update it!

**Comment by hayaokimura** [comment]
@unasuke 
its updated! This PR is ready for review.

**Review by unasuke — APPROVED** [review]
👍 👍 👍 👍

**Pull request merged**
