### PR TITLE
List contributors in about page

### PR DESCRIPTION
**Pull request by okuramasafumi**
CleanShot 2023-10-29 at 18 24 53@2x

### CODE REVIEW

**Review by unasuke — COMMENTED** [review]
@okuramasafumi Could you add the script to generate `contributers.json` for convenience?

**Comment by okuramasafumi** [comment]
It's as simple as

```
gh api \
-H "Accept: application/vnd.github+json" \
-H "X-GitHub-Api-Version: 2022-11-28" \
/repos/kaigionrails/conference-app/contributors > contributors.json
```

so I just mentioned it in a commit message.

**Review by unasuke — APPROVED** [review]
I read the commit message. It's good as MVP.

**Comment by unasuke** [comment]
ref #86

**Pull request merged**
